### ISSUE TITLE
box_auth_service method returns 400 error

### ISSUE THREAD

**Issue by bhaumik55231** [r-box/boxr#138]
I have created a **token.json** file in **~/.boxr-auth** directory. 

![image](https://user-images.githubusercontent.com/26577910/70634472-4ae01a80-1c00-11ea-8beb-85398ea1bd81.png)

**Comment by nathancday** [comment]
My impression is that [400 errors from the Box API](https://developer.box.com/en/guides/api-calls/permissions-and-errors/common-errors/#400-bad-request) are related to malformed request params. Since this is at authentication, I'm guessing this is related to the credentials or the SHA.

Can you confirm that you have authorized your app as outlines [in this section](https://r-box.github.io/boxr/articles/boxr-app-service.html#authorize-app)?
