### ISSUE TITLE
box_previous_versions() not working as expected

### ISSUE THREAD

**Issue by ashirwad** [r-box/boxr#139]
Hello, 

When I use `box_previous_versions()` on a file that only has 1 version, I expect to see the message "_No previous versions for this file found._", but instead I see "_Versions inferred from file modification dates. The box.com API does not provide explicit version information. Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 2, 0_". Is this a bug or I am doing something wrong?

Thanks!

**Comment by nathancday** [comment]
Thanks for pointing this out!

`box_previous_versions()` was looking for a `NULL` in the API response to id files with only a single version, but that element in the results was actually an empty list. So I updated to check for this new empty list response and I think you will find the expected behavior in [this branch](https://github.com/r-box/boxr/tree/is_void). If you want to test it locally `remotes::install_github("r-box/boxr@is_void")`

**Comment by ashirwad** [comment]
Thanks for your prompt reply! I will test the branch and will let you know if the problem is gone or it still persists.

**Comment by ashirwad** [comment]
@nathancday , I tested the branch and `box_previous_versions()` work as expected. You can close the issue if you want. :)
