### ISSUE TITLE
Trouble with box_auth and the OAuth dance

### ISSUE THREAD

**Issue by taylo5jm** [r-box/boxr#143]
Hey all,

I'm having a little trouble with the OAuth dance described in the documentation (https://r-box.github.io/boxr/articles/boxr-app-interactive.html#transfer). 

If I use the code below, I can make it to the first page on Box that asks me to grant permission to my application. After granting permission, I get routed to a page displaying "This site can't be reached, localhost refused to connect."

```
options(httr_oob_default = F)
boxr::box_auth(client_id='XXXXXXXX',
               client_secret = 'XXXXXX')
```
The address in my browser window seems to have a payload with `state` and `code`. From my limited experience with OAuth, I think that I need to use this code to retrieve a token, but there is no prompt in R to do so -- boxr still waits for the browser session to complete.

```
http://localhost:1410/?state=XXXXXXXXXX&code=XXXXXXXXXXXXXXX
```

I also tried to set the `httr_oob_default` option to `TRUE`, but that setting will result in a browser window being opened that says "There seems to be a problem with this app." and "error: invalid_redirect_uri." In R, I get a prompt for the authorization code, but I never get far enough in the process to get a code from Box. 

Any suggestions? It is possible that an issue exists with my firewall settings, however, I remember doing this in the past with no firewall problems and I have tried the dance on both an Ubuntu and OS X remote server. 

Thanks,
Justin

**Comment by nathancday** [comment]
Heyo Justin!

The OAuth dance involves authenticating on your local machine moving all of the relevant files (token-file `~/.boxr-oauth` + the `BOX_CLIENT_ID` and `BOX_CLIENT_SECRET` .Renviron variables) *post auth* to the server, this simulates the caching of credentials. So when you attempt to authenticate from the server, you are using that "cache" we transported over. If you try to pass variables into the auth call from the server you will trigger a new auth request and that will fail because OAuth by design requires browser confirmation from the same address.

If you want a robust solution for accessing Box from your server I'd recommend using the newly supported [`service-apps`](https://r-box.github.io/boxr/articles/boxr-app-service.html#transfer), that use a more durable JWT for authentication and don't require this credentials migration, but do require adding a service account as a collaborator to an existing folder on Box.

Let me know if that doesn't sync with what you are experiencing. Always happy to pop in too, because this server auth stuff is messy and the service app is brand new and not widely tested.

**Comment by taylo5jm** [comment]
Hey Nate,

Thank you for the explanation. I tried to do the OAuth dance again by running `box_auth` on local and then copying over the token, as well as the client ID and client secret. I reset my session and try to use `box_fetch`, which I expect to fail without calling `box_auth` first. It does fail, but `box_auth` with no arguments will also fail due to my refresh token being expired.

```
> boxr::box_auth()
Reading client id from .Renviron
Reading client secret from .Renviron
Auto-refreshing stale OAuth token.
Error in boxr::box_auth() : 
  Login at box.com failed; unable to connect to API.
In addition: Warning message:
Unable to refresh token: invalid_grant
Refresh token has expired 
```
I am confused by this error message, because I thought that I had to have a non-expired refresh token on my local machine to get a new access token. I tried to do the same procedure with a new application on Box, but I get the first error that I described in my original post.

Don't worry about troubleshooting this issue further -- I am afraid there are too many other variables to consider with permissions on Box and whatnot. I will look into the JWT option as an alternative.

Thanks again for your help.
-Justin

**Comment by nathancday** [comment]
Sorry I think I misunderstood how you were handling the authentication originally. I'm not 100% clear on what that error message means, but my guess is it is coming because the redirect URI has changed b/w the original auth and the re-attempt on the server.

Maybe we plan a chori-frie fueled lunch hack, if you don't get the JWT method to an acceptable spot by February 10th?
