### ISSUE TITLE
use service app on shinyapps.io?

### ISSUE THREAD

**Issue by jrosen48** [r-box/boxr#165]
First, thanks for an amazing and well-documented package, it's been a lot of fun to use. I am trying to access a service app on [shinyapps.io](http://shinyapps.io/) via {boxr}.

I can verify that I set up a JWT (JSON) token locally:

```{r}
> box_auth_service()
boxr: Authenticated using OAuth2 (JWT) as faast (AutomationUser_1333220_ppzkIN6vDx@boxdevedition.com, id: 13460778359)
```

However, I'm having some trouble doing this on shinyapps.io---I think because the file system on shinyapps.io is different from RStudio Server (and locally). Here is the error I see:

```{r}
Error in value[[3L]](cond) : 
  [ENOENT] Failed to realize '/home/shiny/.boxr-auth/token.json': no such file or directory
```

Do you have any advice regarding what to pass to the `token_file` argument for `box_auth_service()`---or more general about how to setup a service app on this platform?

Thanks!

Noting this is related to #23 and #56

**Comment by ijlyttle** [comment]
Hi @jrosen48,

Thanks for the kind words!

You are right that you have to specify the token file, but it is important also that the token file be encrypted when on shinyapps and that you be able to provide shinyapps a key so that only "you" can decrypt it.

The general strategy is described in this {gargle} vignette: https://gargle.r-lib.org/articles/non-interactive-auth.html

We adapted this for our use so that we can do test on Box using Travis.

Is this what you are looking for?

**Comment by jrosen48** [comment]
Yes, this is exactly what I was looking to learn about (to do this the right way!). I have this setup on shinyapps.io now. Thank you!
