### ISSUE TITLE
Feature request: Add boxr::box_copy() to the list of existing boxr functions

### ISSUE THREAD

**Issue by ashirwad** [r-box/boxr#167]
One of the folders for the project that I am working on has some sensitive naturalistic driving video data, and consequently only few people have access to it. For the purposes of the analysis, I have shortlisted a list of videos that need to be manually reviewed by some research assistants to extract variables of interest. Since adding those assistants to the main folder is not possible due to project constraints, I was thinking of creating copies of the subset of videos that I need for review purposes in a separate Box  folder and share that with the research assistants.

I see that it's possible to create copies of a file through [this Box API ](https://developer.box.com/reference/post-files-id-copy/) and thought `boxr::box_copy()` would be a good addition to the list of existing `boxr` functions. What do you think @nathancday?

**Comment by nathancday** [comment]
My first thought is it might make more sense to take advantage of Box collaborations for your situation. instead of duplicating files. Video files are large and copies will eat into storage space, there is also the issue of keeping copies synced, but maybe they never change so it doesn't matter. I know the collaboration option allows users to be added to specific files. So you could have them only access a given file and not the entire path. We have the function `box_collab_create()` in master (yet to be CRAN released).

All that to say if the API supports something I think it makes sense that `boxr`should support it too. Would you want take a shot at `box_copy()` using some of the existing functions as templates? Obviously happy to help if you have questions...

**Comment by ashirwad** [comment]
Thanks for your comment, Nate! `box_collab_create()` makes sense. I will take a shot at `box_copy()` as soon as I have some time available.

**Comment by ijlyttle** [comment]
This might make sense as part of a larger effort to wrap the Box API file-update endpoint, discussed in #167.

**Comment by ijlyttle** [comment]
closing in favor of #208
