### ISSUE TITLE
Read csv files from folder

### ISSUE THREAD

**Issue by fmmattioni** [r-box/boxr#203]
I was wondering if there is a faster way to read multiple `.csv` files from a folder?

My current approach is:

```r
boxr::box_search_files(query = ".csv") %>%
  dplyr::as_tibble() %>% 
  dplyr::rowwise() %>% 
  dplyr::mutate(
    data = boxr::box_read_csv(file_id = id) %>% list()
  )
```

However, that is quite slow. Any ideas?

**Comment by nathancday** [comment]
How many files are you downloading and how big are they? I think those will be the biggest speed factors. i.e. Could you do more filtering on Box instead of pulling all of the CSVs.

`box_read_X()` functions have to download the files (to a tmp directory) before the read-in as R objects, so bandwidth could also play an issue.

Aside from that `data.table::fread()` has been my preference for large CSV files, b/c it seems to be the fastest R option.

**Comment by fmmattioni** [comment]
I have about 30 files, and each one is about 2 Mb..

I have a workaround, in which I process the data as I need on my desktop and then save it as `.rds` in box. Then, I only need to read that file.

I guess the slow part is indeed downloading the files.. there is no way around this, right?

**Comment by nathancday** [comment]
Always been my experience that bandwidth is more limiting that machine IO speed. And there is no way to get around downloading files prior to read in with current Box API.

FWIW I saw some bench marking at RStudio global that showed `arrow::read_csv_arrow()` being even faster than `data.table::fread()`.

**Comment by fmmattioni** [comment]
Wow, that is great to hear! I am going to look it up!
