### ISSUE TITLE
box_fresh_auth() Error: `cache` must be a valid filename

### ISSUE THREAD

**Issue by JoeBradlee** [r-box/boxr#219]
Hi there,

Trying to use boxr to read some spreadsheets into R. When I try, I get the error; "Auto-refreshing stale OAuth token.
Error in boxGet(file_id, local_file = temp_file, version_id = version_id,  : 
  Error downloading file id xxxxxxxxx: Client error: (403) Forbidden)
  
  Apparently you have to use box_fresh_auth().
  
  I type in both  `box_fresh_auth()` and `box_fresh_auth(cache = "~/.boxr-oauth")` and I get the following error:
  Error: `cache` must be a valid filename
  
  What am I doing wrong?

**Comment by nathancday** [comment]
Have you ever used `box_auth()`? `box_fresh_auth()` can only be used after originally connecting with `box_auth`. [Read this for more.](https://r-box.github.io/boxr/articles/boxr-app-interactive.html) 

That error message says Box doesn't grant you access/permission to that fileID.

**Comment by JoeBradlee** [comment]
> Have you ever used `box_auth()`? `box_fresh_auth()` can only be used after originally connecting with `box_auth`. [Read this for more.](https://r-box.github.io/boxr/articles/boxr-app-interactive.html)
> 
> That error message says Box doesn't grant you access/permission to that fileID.

Yup. I authenticated with no issues.

**Comment by nathancday** [comment]
No need to use `box_fresh_auth()`then. If you can't `box_read()` or `box_dl()` after an succesful authentication then its a file permission problem and `boxr` can't really help you with that. Does that make sense?

**Comment by danielruss** [comment]
@nathancday   I get the same error.  

Looking at the code, it appears the problem is that  file.exists("\~/.boxr-oauth") return TRUE but fs::file_exists("~/.boxr-oauth") returns FALSE.

Looking deeper into the fs::file_exists function: 

- path.expand("\~/.boxr-oauth") ==> 
     "C:/Users/<USER>/Documents/.boxr-oauth"

- fs::file.exists("C:/Users/<USER>/Documents/.boxr-oauth") ==> 
     C:/Users/<USER>/Documents/.boxr-oauth    
     TRUE

- file.exists("C:/Users/ahearntu/Documents/.boxr-oauth") ==> 
   [1] TRUE

the path_expand is working ok (so R is getting the \~/ correct), if the user gives the complete path fs::file.exists() it works ok (returns true), but fs::file.exists("\~/.boxr-oauth") 

can you change the assertion to use file.exists instead of fs::file_exist?

**Comment by nathancday** [comment]
Interesting because we switched to `fs` in order to break things less. I can't reproduce on my local with this reprex:
```

path = "~/.boxr-oauth"
file.exists(path)
#> [1] TRUE
fs::file_exists(path)
#> ~/.boxr-oauth 
#>          TRUE
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] crayon_1.3.4    digest_0.6.27   withr_2.4.0     lifecycle_0.2.0
#>  [5] magrittr_2.0.1  reprex_2.0.1    evaluate_0.14   pillar_1.4.7   
#>  [9] highr_0.8       stringi_1.5.3   rlang_0.4.10    cli_3.2.0      
#> [13] rstudioapi_0.13 fs_1.5.0        vctrs_0.3.6     ellipsis_0.3.1 
#> [17] rmarkdown_2.6   tools_4.0.3     stringr_1.4.0   glue_1.6.1     
#> [21] xfun_0.20       yaml_2.2.1      compiler_4.0.3  pkgconfig_2.0.3
#> [25] htmltools_0.5.1 knitr_1.30      tibble_3.0.5
```

It seems like `fs:file_exists()` is behaving as expected. Are you running on Windows, maybe different package versions?

**Comment by danielruss** [comment]
@nathancday  The problem is on windows.  I was working with someone running on a windows machine.  I'll get the details back to you as soon as I hear back (although Monday is a US Federal holiday so it may be Tuesday).  I know we just updated a bunch of packages when she tested my PR.  Maybe the update alone would have fixed the problem.  

I don't have problems on the mac.

**Comment by nathancday** [comment]
Thanks for the update that makes sense if its a Windows path problem. Disappointed that `fs` is causing this, b/c that's what it's supposed to fix is cross-plat path issues but here we are. I have to problem falling back to base `file.exists()`, thanks for figuring it out.

@JoeBradlee are you on Windows too? Sorry for my earlier misunderstanding.

**Comment by danielruss** [comment]
got the results...

 fs::file_exists( "~/.boxr-oauth")
~/.boxr-oauth
FALSE
 file.exists("~/.boxr-oauth")
[1] TRUE

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/154876245-cc0a2b6c-0b16-4014-8dae-bacbbd2ec377.png)
![image2](https://user-images.githubusercontent.com/3767675/154876262-5dcd27c4-ee6a-41c2-a826-d2a6ec71d5da.png)

**Comment by ijlyttle** [comment]
I think the problem may be that when we switched to {fs}, we did so incompletely.

https://github.com/r-box/boxr/blob/28ccd2610922b53e0275d4d128f29781b92970e0/R/boxr_auth.R#L70-L72

To be consistent, we will need to specify the `cache` default using something like`cache = fs::path_expand("~/.boxr-oauth")`.

As I understand, this is a whole "thing" where R for Windows (via `path.expand()`) defines `~` differently than does Python, etc. `fs::path_expand()` [tries to align that](https://fs.r-lib.org/reference/path_expand.html).

Let me look into changing the defaults to bring everything into alignment, which would require Windows users to either move their cache file or authorize again (sorry).

**Comment by nathancday** [comment]
Tried and confirmed that error exists on Windows, no luck with `fs::path_expand()` though.
> file.create("~/.boxr-auth")
[1] TRUE
> path = "~/.boxr-auth"
> file.exists(path)
[1] TRUE
> fs::file_exists(path)
~/.boxr-auth 
       FALSE 
> fs::file_exists(fs::path_expand(path))
C:/Users/Administrator/.boxr-auth 
                            FALSE

**Comment by ijlyttle** [comment]
How about this on Windows?

```r
path = "~/.boxr-auth"
file.create(fs::path_expand(path))
fs::file_exists(path)
```

**Comment by nathancday** [comment]
Ahh yes that works (and makes sense). Maybe `fs::file_create()` does path expansion on the fly? 

I'm not crazy about using `fs` in the first place, when the base alternative is working. This "gotcha" is a wee bit annoying for such a common path abbreviation. I could go either way for fixing it.

**Comment by danielruss** [comment]
I am going to push this to the fs package developers.  However, even if they fix the bug, windows users will be dependent on a newer version of fs.

**Comment by ijlyttle** [comment]
@danielruss I'm pretty sure that the fs behavior is an intentional design choice, meant to implement other languages' notion of a home directory in R.

I think the challenge here is how implement that idea here. I'm going to think about trying both locations for *reading*, but to settle on a standard location for *writing* the cached token.

**Comment by jennybc** [comment]
I caught wind of this because I watch fs, where an issue linked to this.

(Yes it's a very intentional design decision in fs, not a bug <https://fs.r-lib.org/reference/path_expand.html>. 

For what boxr is doing (storing a token), you probably want to use either `tools::R_user_dir()` (introduced in R 4.0.0) or `rappdirs::user_cache_dir())` (would work on earlier versions of R) as the location. That's sort of the morally right place to put the token anyway and it relieves you of your Windows vs everything else dilemma.

The transition from the old way to the new way is a bit painful (I went through this myself with gargle).

**Comment by gaborcsardi** [comment]
Also note that CRAN does not like the places rappdirs uses by default, so you'd need to use `R_user_dir()` on newer R versions, and since they do not test on older versions rappdirs is fine on those. Or you can use `backports::R_user_dir()` which should be always fine: https://github.com/r-lib/backports#backports-for-r-versions-prior-to-400

**Comment by danielruss** [comment]
@nathancday @ijlyttle  I would be happy to help prepare a PR.  If not, let me know how you want to move forward.

**Comment by ijlyttle** [comment]
@jennybc, @gaborcsardi Thanks! I think I understand better what is *supposed* to happen with `tools::R_user_dir()` and `backports::R_user_dir()`. I have not used {backports} before, but this sounds like a good learning experience.

@danielruss @nathancday I think this might be a bigger undertaking than I thought a few "comments" ago. That said, I think it's a good direction to try out.

Perhaps there is a short-term fix: when reading, look in both places - and this longer-term fix. I need to spend a little time with pen and paper (i know) to make things clearer for me; I'll come back with a proposal soon.

**Comment by nathancday** [comment]
Thanks for the pointer to `tools::R_user_dir()` @jennybc,  that is a nicer way to handle token paths.
