### ISSUE TITLE
Error when deploying shinyapp with boxr 

### ISSUE THREAD

**Issue by RomaneTavernier** [r-box/boxr#221]
Hello, 

I developed a shiny app in which the user can save the scenario they did in a new Excel file stocked in the Box application. 

The Shiny App works when run in the R session and well write a new Excel file in the Box application. I did the link between the R session and the Box application thanks to the "boxr" package. 
However, I can't deploy the Shiny App. When I try to do so, it well creates a link to a web page, but the element of the application do not appear in it, and the application link crashes in a short-time period.

I tried two scenario: 

1. I put the file .boxr-oauth outside the folder "www" and got the following error message in the log from ShinyApp: 
  "createTcpServer: address already in use 
   Error: Failed to create server
   Retrying in 1 seconds.
   129: <Anonymous>  "

2. I put the file .boxr-oauth in the folder "www" and got the following error message in the log from ShinyApp: 
    "Error: Failed to create local cache ('./www/.boxr-oauth')
    Retrying in 1 seconds."

Does anyone know what the issue could be and how to resolve it? 

Thanks in advance for your time

**Comment by nathancday** [comment]
ShinyApps is a tricky situation and one of the reasons we wanted to make the option for "Service App" authentication in `boxr`
https://r-box.github.io/boxr/articles/boxr-apps.html#service-app-1

Copying over the authentication files like you are trying **should** work, but will require constant manual updating. Using a Service App should bypass the repeated copying because you are not longer relying on oAuth and instead using a stored JWT token.

I don't think that solves your problem immediately, but might open up new things to try. ShinyApps.io is a tricky problem because it has restrictions and you lack full control over the server environment. Hosting a Shiny server would allow more control.
