### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#76]
Rework testing and `.travis.yml` so that TravisCI will run tests.

**Comment by nathancday** [comment]
What is the plan to tackle this?

Considering the remote-server/OAuth limitations of the package at present I don't see a way to do this

**Comment by ijlyttle** [comment]
I have to confess that I can't remember exactly what I had in mind when I wrote this issue. I hope to block off some time soon to get everything in shape for CRAN. 

Needless to say, I appreciate your finding the typo in the test I wrote!

Also - just a note to self to look at removing test 9 (thanks for the suggestion).

**Comment by nathancday** [comment]
Thanks for accepting my PR, IMO the testing works well now.

Also regarding the CRAN release, I've started working on #75 and I plan to submit a PR with that this weekend. Happy to help share some of the release burden :)

**Comment by ijlyttle** [comment]
#75 - ooooh, thanks! I think I will take you up on your kind offer!

**Comment by ijlyttle** [comment]
I have revived the local testing.

Immediate tasks: 

- [ ] get all tests passing (currently problems with JSON (`test_05`) and versions (`test_08`)
- [ ] use temp dir for the local side of the tests
- [ ] create a custom folder on box for the remote tests - each run of `test()` will get a unique folder on box, so that tests might be run concurrently on travis

Next:

- [ ] use ssh encryption on the `.boxr-oauth` file; see [Jenny Bryan's vignette](https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html)

**Comment by nathancday** [comment]
I'm passing all tests with boxr@d450690. I know screenshots suck...

![image](https://user-images.githubusercontent.com/808225/53290372-04085d80-3771-11e9-8f40-b8e68b5d4562.png)

AFAIK we are using a temp dirs for the local side of testing

I don't think the concurrency on Travis is valuable, because Box API already restricts each account to a single concurrent transfer, thus the behavior of `box_fetch()/box_push()`

**Comment by ijlyttle** [comment]
Gah!

I'll have to think some more about the concurrency...

It looks like it creates a temporary directory in the working directory: https://github.com/brendan-r/boxr/blob/42b572cfd09960fabb1683ce907dc3b043909483/R/boxr__internal_misc.R#L188-L197

On my last CRAN submission, I was initially rejected for having code that wrote to the working directory - even though that code never ran on the CRAN checks (which would be the case here) - I think it will be cleaner if we can write to the `tempdir()`.

**Comment by nathancday** [comment]
Oh I see what you are saying about the tests. I agree that should become `tempdir()`. I think all we'd need to do is adjust the downstream `local_dir` arguments to make it work

**Comment by ijlyttle** [comment]
Also consider this: https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html

**Comment by nathancday** [comment]
Gargle looks great! I will take a look at this for the JWT/Travis solution

**Comment by ijlyttle** [comment]
Hi @nathancday,

 I was looking at [this comment](https://github.com/r-box/boxr/issues/92#issuecomment-476819592) you had made - in particular about getting a "developer enterprise" account through <https://developers.box.com>.

Should we (or maybe you have already) apply for one on behalf of our "r-box" organization? 

Do you think this might remove the concern we have for CI making simultaneous requests of the Box API?

Questions, Questions, Questions....

**Comment by nathancday** [comment]
I have been using my personal email so far to set up the JWT stuff. But since each Box account (the Developer bit is just a voluntarily level up) is really just an email address, all we would need is something like 'r-box@gmail.com', to have a permanent organization account.

I'm not sure the logistics of that email account (login sharing, password storage, etc), but I think it's a good idea in terms of the package's/org's autonomy. I'm planning to work on the Travis/gargle bit this weekend and would be happy to set it up, if you agree it's a good idea.

I'm not sure about simultaneous request, I believe the Oauth2 route is restricted to only one at a time...

**Comment by ijlyttle** [comment]
Sounds good to me, please go ahead - it would be great if we can find a way around the simultaneous request restriction (or figure out how to manage it).

I am planning to work more on the function-documentation this weekend, but if you need any support on the testing/JWT side - just let me know; I'd be happy to hop on a call, even if you "just" need to sound through some ideas, i.e. [rubber-duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging).

**Comment by nathancday** [comment]
Hey @ijlyttle, how does your schedule look for a quick call about testing?

**Comment by ijlyttle** [comment]
How about 13h00 CDT / 14h00 EDT?

**Comment by nathancday** [comment]
Wonderful. What's your preferred video chat service?

**Comment by ijlyttle** [comment]
Let me send you an email

**Comment by nathancday** [comment]
Turns out if you pass the gargle secret `BOXR_PASSWORD` as an `env` variable in `.travis.yml` it works. https://travis-ci.org/r-box/boxr/jobs/564465107

```
...
boxr: Authenticated at box.com as Boxr Tester (boxr.tester@gmail.com)
══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 95 | SKIPPED: 3 | WARNINGS: 0 | FAILED: 0 ]
> 
> proc.time()
   user  system elapsed 
  5.408   0.212 120.735 

Done. Your build exited with 0.
```

**Comment by ijlyttle** [comment]
It sounds like progress, but (if I understand correctly) `BOXR_PASSWORD` is something we are meant to keep secure?

**Comment by nathancday** [comment]
Yes. Too me it just narrows the problems to something with gargle picking
up an encrypted variable from the Travis settings

**Comment by nathancday** [comment]
I expected this to auto-close when I merged the JWT branch. I feel like is resolved now.

**Comment by ijlyttle** [comment]
Closed!

**Comment by nathancday** [comment]
My turn on the crazy-idea-train...

Right now the box_search() tests are set to skip, because the Box search engine takes ~10 minutes to index new material, which is not enough time in the context of testing. We could accommodate testing them if we adjusted the test procedure a bit.

Instead of use the 0 folder for all of the tests we could have a long-term and short-term folder. Short-term would behave identical to how we treat 0 right now, wipe each time and re-build. Long-term could have a set of text files that are "relatively" permanent which would mean they could be indexed against with `box_search`.

What do you think? Maybe more of a next release thing, but if you think it would be worthwhile, I'll take this idea and start a new issue around it

**Comment by nathancday** [comment]
@ijlyttle can you read the above ^^^ not sure what happens if you still get notifications for closed issues or not

**Comment by ijlyttle** [comment]
I get the notifications - yes - please, open an issue so that we can look set this up going forward!
